apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: dummy-pipelines-
  labels:
    appstudio.openshift.io/application: bonfire-image
    appstudio.openshift.io/component: bonfire-image
spec:
  pipelineSpec:
    tasks:
      - name: echo
        taskSpec:
          steps:
            - name: echo
              image: registry.access.redhat.com/ubi9/ubi@sha256:66233eebd72bb5baa25190d4f55e1dc3fff3a9b77186c1f91a0abdb274452072
              script:
                #!bin/bash
                
                echo "Hello From Konflux"
